[package]
name = "parity-wordlist"
version = "1.3.0"
description = "Word list used to generate brain wallets for Parity."
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]
repository = "https://github.com/paritytech/wordlist"

[dependencies]
lazy_static = "1.0"
rand = "0.6"
itertools = "0.5"
